version: ~> 1.0
os: linux
dist: xenial
language: python

services:
    - xvfb

addons:
    apt:
      packages:
        - herbstluftwm
        - libxkbcommon-x11-0
env:
  global:
    - secure: "hBCzCVHaSb43+jT7b+hwjB2Xb0nfJqjoTNA7fVye7f23zgYGTemlCuRJUeAKjnwqKdfuevNklSRabMNnoI2zW3T19VV4KdwrmyA/o0O1tsR3qjvXXARd1MTte37ZM2XTMSs4Nxhea5HpXzy8BQXGFNvkZuGmhgNJCoIgaNv047MM3t8lnBRhJNXWc9OaYhqRQ8zw+beezGMdosV4AgOVTr+6K1aZcUOVDsI3sgib0sPq9zcCnaCsolZgJGb2iXUVrxZ2uNeEhKgKk7FScEgiLanaKiUJLOUeQoG5DczVdtfhDRLfbLk8bc7IfRZtaeVCaTgjvwb2ZW7LTi1rXhoy9jsNzKwROUrwsho8S710N7VYTENIbWqAvR7ZwYuGTdwtQiOXvjPvaYhPByK0XCUi98P65s/JDhwKE7mki4QD7E3aAxBJc0h9tzRjZVpG7k+iZuPHy93CEHwkbZFPGFYrDd29kWpNavsBrEQtRxbUkvjjA9vUKaNXBakm9VIO7MAyYFdj8vx9BovQ35Rw5O0kpF7jwY6pch9fBrVKI+G1iTDs/hOx8Qf8mPsb8pltCar3DRIxXd9nNGmR6seb0BGnA2l8cCcYa6VcnfLZecJnYOLwi0/n8i0d3YK6dN/r0hY2MPNKnwb1Fkr29HnObRrcq9zoPgdNRsl+9Z75JcQBghk="
    - DOCS_REQUIREMENTS: "dev-requirements.txt"
    - DOCTR_VERSIONS_MENU: 1
    - PYTHON_LINT_OPTIONS="typhos --verbose"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --remove channels defaults
  - conda config --add channels conda-forge
  # Useful for debugging
  - conda info -a
  - conda build -q conda-recipe --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"
  # Manage conda environment
  - conda create -n typhos-env python=$TRAVIS_PYTHON_VERSION typhos pip pyqt --file dev-requirements.txt
  - source activate typhos-env
  # Useful for debugging
  - conda list

before_script:
  # Run windows manager
  - "herbstluftwm &"
  - sleep 1

script:
  - |
    if [[ "$BENCHMARK" == "1" ]]; then
      coverage run run_tests.py --show-capture=no --benchmark-only
    else
      coverage run run_tests.py --show-capture=no
    fi
  - coverage report -m

after_failure:
  - cat logs/run_tests_log.txt

stages:
  - test
  - name: deploy
    if: (branch = master OR tag IS present) AND type != pull_request

import:
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/python-linter.yml@adjustments
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/docs-build.yml@adjustments
  - source: hhslepicka/pcds-ci-helpers:travis/shared_configs/python-tester.yml@adjustments
    mode: deep_merge
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml@adjustments
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml@adjustments
  - hhslepicka/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml@adjustments