{% set data = load_setup_py_data() %}

package:
    name    : typhos
    version : {{ data.get('version') }}

source:
    path: ..

build:
  noarch: python
  entry_points:
    - typhos = typhos.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyqt >=5
    - qtpy
    - coloredlogs
    - numpy
    - numpydoc
    - ophyd >=1.5.0
    - pcdsutils
    - pydm
    - pyqtgraph
    - qdarkstyle
    - qtawesome
    - qtconsole
    - timechart

about:
  home: https://github.com/pcdshub/typhos
  doc_url: https://pcdshub.github.io/typhos
  dev_url: https://github.com/pcdshub/typhos
  summary: 'Automatic-yet-customizable Graphical User Interface Generation for Ophyd Devices'
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md

test:
  imports:
    - typhos
    - typhos.cli
  commands:
    - typhos --help

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz